### ISSUE TITLE
error when doing catkin_make

### ISSUE THREAD

**Issue by Jaetriel** [gisbi-kim/FAST_LIO_SLAM#14]
Hello @gisbi-kim , thank you for your amazing work. I'm trying to use FAST_LIO_SLAM but I'm getting an error when I clone your repo in my catkin_ws/src and doing catkin_make:
`/home/gl/catkin_ws/src/FAST_LIO_SLAM/FAST-LIO/include/common_lib.h:8:10: fatal error: fast_lio/Pose6D.h: No such file or directory
 #include <fast_lio/Pose6D.h>
`
I'm pretty sure I have all the dependencies installed. I tried using FAST_LIO on its own and SC_A_LOAM package as well and they work on their own but if I try to play the KAIST_03 like in your video I am getting the errors for `failed to find match for field xx` and nothing shows in RViz because FAST_LIO package doesn't have your changes in the code.
Any idea what is this header file and where I can find it?

**Comment by ManChrys** [comment]
@Jaetriel  yeah i had the same thing.

check #10

**Comment by Jaetriel** [comment]
@ManChrys yes, I had a look at it but my folder structure looks identical to yours and I still don't see any data shown in RViz

**Comment by ManChrys** [comment]
Yeah it doesn't work that's why you can't see it on rviz. Kaist-03 example doesn't have ring ambient and all other fields that's why you have these warnings and no visual results on rviz. Try another examples.

**Comment by Jaetriel** [comment]
I tried Riverside-02 as well but I get the same result, which is weird because they are the examples given in the readme of the repo, so I am thinking that maybe I am missing something?

**Comment by ManChrys** [comment]
Yeah probably all examples are not suitable. If I find a suitable example I'll share it with you.

**Comment by Jaetriel** [comment]
@ManChrys thank you, I've managed to run the package with my own datasets, so everything seems to be working fine and I will close this issue now
